first_project:           # must match profile in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: spark
      method: http             # <-- must be http for Databricks SQL endpoint
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      schema: your_schema_name   # replace with your schema
      threads: 1
