name: dbt_dbt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbx_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbx dbt-core dbt-spark

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databricks/config
          echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databricks/config
          echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databricks/config

      - name: Run dbx job
        run: |
          dbx deploy --environment prod --jobs all
          dbx launch --job <your_job_name> --environment prod
