name: dbt_dbx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-spark

      - name: Configure Databricks connection
        run: |
          export DATABRICKS_SERVER_HOSTNAME=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_HTTP_PATH=${{ secrets.DATABRICKS_HTTP_PATH }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}

      - name: dbt debug
        run: dbt debug --profiles-dir .

      - name: dbt run
        run: dbt run --profiles-dir .

      - name: dbt test
        run: dbt test --profiles-dir .
