name: dbt_dbx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core
          pip install dbt-spark[PyHive]

      - name: dbt debug
        run: dbt debug --profiles-dir ci_profiles --profile first_project

      - name: dbt run
        run: dbt run --profiles-dir ci_profiles --profile first_project

      - name: dbt test
        run: dbt test --profiles-dir ci_profiles --profile first_project
